export type LedgerEntry = {
  type?: string;
  amount?: number;
  fundBatchId?: string;
  createdAt?: Date | { toDate(): Date } | null;
  details?: string;
  metadata?: { source?: string };
};

export type AnniversaryFundBatch = {
  id: string;
  tenureValue?: number;
  tenureUnit?: 'Days' | 'Weeks' | 'Fortnights' | 'Months' | 'Years';
  createdAt?: Date | { toDate(): Date } | null;
};

export type AnniversaryWithdrawalRequest = {
  amount?: number;
  source?: string;
  status?: string;
  anniversaryWindowIds?: string[];
};

const DURATION_IN_DAYS = {
  Days: 1,
  Weeks: 7,
  Fortnights: 14,
  Months: 30.4375,
  Years: 365.25,
} as const;

const DAY_MS = 24 * 60 * 60 * 1000;

function asDate(value: Date | { toDate(): Date } | null | undefined): Date | null {
  if (!value) return null;
  const date = value instanceof Date ? value : value.toDate();
  return Number.isNaN(date.getTime()) ? null : date;
}

function addCalendarYears(value: Date, years: number): Date {
  const result = new Date(value.getTime());
  const month = result.getUTCMonth();
  result.setUTCFullYear(result.getUTCFullYear() + years);
  // February 29 anniversaries fall on February 28 in non-leap years.
  if (result.getUTCMonth() !== month) result.setUTCDate(0);
  return result;
}

/**
 * Finds annual five-day withdrawal windows for fund batches locked for more
 * than two years. Each window permits 20% of profit generated by that batch in
 * the preceding investment year. The maturity anniversary itself is excluded.
 */
export function calculateFundBatchAnniversaryWindow(input: {
  fundBatches: AnniversaryFundBatch[];
  entries: LedgerEntry[];
  withdrawalRequests?: AnniversaryWithdrawalRequest[];
  now?: Date;
}) {
  const now = input.now || new Date();
  const activeWindows = input.fundBatches.flatMap((batch) => {
    const lockedAt = asDate(batch.createdAt);
    const unit = batch.tenureUnit;
    const tenureDays = unit ? Number(batch.tenureValue || 0) * DURATION_IN_DAYS[unit] : 0;
    if (!lockedAt || tenureDays <= 2 * DURATION_IN_DAYS.Years) return [];

    const tenureYears = tenureDays / DURATION_IN_DAYS.Years;
    // The maturity anniversary is not a restricted-profit window because the
    // lock has ended. A three-year batch therefore receives years one and two.
    for (let year = 1; year < tenureYears; year += 1) {
      const opensAt = addCalendarYears(lockedAt, year);
      const closesAt = new Date(opensAt.getTime() + 5 * DAY_MS);
      if (now < opensAt || now >= closesAt) continue;

      const profitPeriodStartsAt = addCalendarYears(lockedAt, year - 1);
      const generatedProfit = input.entries
        .filter((entry) => {
          const createdAt = asDate(entry.createdAt);
          return entry.type === 'ProfitDistribution' &&
            entry.fundBatchId === batch.id &&
            Boolean(createdAt && createdAt >= profitPeriodStartsAt && createdAt < opensAt);
        })
        .reduce((sum, entry) => sum + Math.max(0, Number(entry.amount || 0)), 0);

      return [{
        id: `${batch.id}:year-${year}`,
        fundBatchId: batch.id,
        anniversaryYear: year,
        opensAt,
        closesAt,
        generatedProfit: toCents(generatedProfit),
        allowance: toCents(generatedProfit * 0.2),
      }];
    }
    return [];
  });

  const windowIds = activeWindows.map((window) => window.id);
  const relevantRequests = (input.withdrawalRequests || []).filter((request) =>
    request.source === 'AnniversaryProfit' &&
    request.status !== 'Rejected' &&
    request.anniversaryWindowIds?.some((id) => windowIds.includes(id))
  );
  const pendingUsed = relevantRequests
    .filter((request) => request.status === 'Pending')
    .reduce((sum, request) => sum + Math.max(0, Number(request.amount || 0)), 0);
  const approvedUsed = relevantRequests
    .filter((request) => request.status === 'Approved')
    .reduce((sum, request) => sum + Math.max(0, Number(request.amount || 0)), 0);
  const generatedProfit = toCents(activeWindows.reduce((sum, window) => sum + window.generatedProfit, 0));
  const allowance = toCents(activeWindows.reduce((sum, window) => sum + window.allowance, 0));

  return {
    isOpen: activeWindows.length > 0,
    activeWindows,
    windowIds,
    generatedProfit,
    allowance,
    pendingUsed: toCents(pendingUsed),
    approvedUsed: toCents(approvedUsed),
    availableToWithdraw: Math.max(0, toCents(allowance - pendingUsed - approvedUsed)),
    // Approved requests are already consumed in the ledger. Everything else
    // in the 20% allowance remains unavailable for reinvestment in the window.
    reinvestmentReserve: Math.max(0, toCents(allowance - approvedUsed)),
  };
}

/**
 * Normalizes a monetary value to the smallest supported NGN unit (one kobo).
 * Keeping this at the domain boundary prevents recurring binary fractions from
 * leaking into Firestore balances and transaction amounts.
 */
export const roundCurrency = (value: number) => {
  if (!Number.isFinite(value)) throw new Error('Currency value must be a finite number.');
  return Math.round((value + Math.sign(value) * Number.EPSILON) * 100) / 100;
};

const toCents = roundCurrency;

/**
 * Splits a currency total proportionally while guaranteeing that every share
 * is in kobo and that the shares add back to the exact rounded total.
 */
export function allocateCurrencyByWeights(total: number, weights: number[]): number[] {
  const normalizedTotal = roundCurrency(total);
  const normalizedWeights = weights.map((weight) =>
    Number.isFinite(weight) && weight > 0 ? weight : 0
  );
  const totalWeight = normalizedWeights.reduce((sum, weight) => sum + weight, 0);
  if (normalizedTotal < 0 || totalWeight <= 0) {
    throw new Error('Currency allocation requires a non-negative total and positive weights.');
  }

  const totalKobo = Math.round(normalizedTotal * 100);
  const rawShares = normalizedWeights.map((weight) => (totalKobo * weight) / totalWeight);
  const sharesInKobo = rawShares.map(Math.floor);
  const remainder = totalKobo - sharesInKobo.reduce((sum, share) => sum + share, 0);

  const remainderOrder = rawShares
    .map((share, index) => ({ index, fraction: share - Math.floor(share) }))
    .sort((a, b) => b.fraction - a.fraction || a.index - b.index);

  for (let index = 0; index < remainder; index += 1) {
    sharesInKobo[remainderOrder[index].index] += 1;
  }

  return sharesInKobo.map((share) => share / 100);
}

export function allocatePartialRepayment(
  amountPaid: number,
  installment: { principal: number; interest: number; payment: number }
) {
  if (!Number.isFinite(amountPaid) || amountPaid <= 0 || installment.payment <= 0) {
    throw new Error('Repayment amount and scheduled payment must be positive.');
  }
  const normalizedAmount = roundCurrency(amountPaid);
  const normalizedPayment = roundCurrency(installment.payment);
  if (normalizedAmount > normalizedPayment) {
    throw new Error('Repayment exceeds the scheduled installment.');
  }

  const ratio = Math.min(1, normalizedAmount / normalizedPayment);
  const principal = toCents(installment.principal * ratio);
  const interest = toCents(normalizedAmount - principal);
  return { principal, interest, ratio };
}

export function calculateInvestorPortfolioValue(entries: LedgerEntry[]): number {
  return toCents(entries.reduce((total, entry) => {
    const amount = Number(entry.amount || 0);
    if (entry.type === 'Deposit' || entry.type === 'ProfitDistribution') return total + amount;
    if (entry.type === 'Withdrawal' || entry.type === 'Zakat') return total - Math.abs(amount);
    return total;
  }, 0));
}

export function calculateAvailableProfit(entries: LedgerEntry[], reserved = 0): number {
  const earned = entries
    .filter((entry) => entry.type === 'ProfitDistribution')
    .reduce((sum, entry) => sum + Math.max(0, Number(entry.amount || 0)), 0);
  const consumed = entries
    .filter((entry) =>
      entry.type === 'Withdrawal' &&
      (entry.metadata?.source === 'ProfitReinvestment' ||
        entry.metadata?.source === 'ShortTermProfit' ||
        entry.metadata?.source === 'AnniversaryProfit' ||
        !entry.metadata?.source ||
        entry.details === 'Profit Reinvestment')
    )
    .reduce((sum, entry) => sum + Math.abs(Number(entry.amount || 0)), 0);
  return Math.max(0, toCents(earned - consumed - reserved));
}
