import type { PrimaryPortal } from '@/lib/access-control';
import type { SupportedLanguage } from '@/lib/localization';

export type GuideText = Record<SupportedLanguage, string>;
const text = (en:string, ha:string, ig:string, yo:string):GuideText => ({en,ha,ig,yo});
export type GuideTopic = {id:string;title:GuideText;steps:[GuideText,GuideText,GuideText];tip:GuideText;href:string;visual:'profile'|'bank'|'receipt'|'signature'|'schedule'|'workflow'|'dashboard'};
export const guideLabels = {
  title:text('Your NAL visual guide','Jagoran NAL na gani','Nduzi NAL a na-ahụ anya','Ìtọ́nisọ́nà NAL aláwòrán'),
  guide:text('User guide','Jagorar amfani','Nduzi onye ọrụ','Ìtọ́nisọ́nà olùlò'),
  intro:text('Learn the process at your own pace. Reading this guide does not submit requests or change balances.','Koyi yadda ake aiki a hankali. Karanta jagora ba ya aika buƙata ko canza kuɗi.','Mụta usoro n’oge gị. Ịgụ nduzi a anaghị ezipụ arịrịọ ma ọ bụ gbanwee ego.','Kọ́ ẹ̀kọ́ ní ìrọ̀rùn rẹ. Kíkà ìtọ́nisọ́nà yìí kò fi ìbéèrè ránṣẹ́ tàbí yí iye owó padà.'),
  example:text('Illustration only — not your live account','Misali kawai — ba ainihin asusunka ba','Ihe atụ naanị — ọ bụghị akaụntụ gị','Àpẹẹrẹ nìkan — kì í ṣe àkọọ́lẹ̀ rẹ'),
  next:text('Next','Gaba','Na-esote','Tó kàn'), back:text('Back','Baya','Laghachi','Padà'),
  later:text('Continue later','Ci gaba daga baya','Gaa n’ihu mgbe e mesịrị','Tẹ̀síwájú lẹ́yìn náà'),
  read:text('I have read this topic','Na karanta wannan batu','Agụọla m isiokwu a','Mo ti ka àkòrí yìí'),
  open:text('Open this section','Buɗe wannan sashe','Mepee ngalaba a','Ṣí abala yìí'),
  finish:text('Finish guide','Kammala jagora','Mechaa nduzi','Parí ìtọ́nisọ́nà'),
  restart:text('Start again','Sake farawa','Malite ọzọ','Bẹ̀rẹ̀ lẹ́ẹ̀kan sí i'),
  saved:text('Reading progress is saved on this device. You can reopen the guide at any time.','Ana ajiye ci gaban karatu a wannan na’ura. Za ka iya sake buɗe jagora.','A na-echekwa ọganihu ịgụ na ngwaọrụ a. Ị nwere ike imepee nduzi ọzọ.','A ń fi ìpele kíkà pamọ́ lórí ẹ̀rọ yìí. O lè tún ṣí ìtọ́nisọ́nà.'),
  unavailable:text('Progress cannot be saved on this device; the guide still works.','Ba a iya ajiye ci gaba a wannan na’ura; jagora yana aiki.','Enweghị ike ichekwa ọganihu na ngwaọrụ a; nduzi ka na-arụ ọrụ.','A kò lè fi ìpele pamọ́ lórí ẹ̀rọ yìí; ìtọ́nisọ́nà ṣì ń ṣiṣẹ́.'),
  topics:text('Topics','Batutuwa','Isiokwu','Àwọn àkòrí'),
  ready:text('Guide complete','An kammala jagora','Emechara nduzi','Ìtọ́nisọ́nà ti parí'),
  action:text('Where to go','Inda za ka je','Ebe ị ga-aga','Ibi tí o máa lọ'),
  tip:text('Important','Muhimmi','Ihe dị mkpa','Pàtàkì'),
  settings:text('Learn how to use your account, make payments and follow approvals.','Koyi amfani da asusunka, biyan kuɗi da bin amincewa.','Mụta iji akaụntụ gị, ịkwụ ụgwọ na iso nkwado.','Kọ́ bí a ṣe ń lo àkọọ́lẹ̀, sanwó àti tẹ̀lé ìfọwọ́sí.'),
};

const navigation:GuideTopic = {id:'navigation',visual:'dashboard',href:'dashboard',title:text('Find your way around','San hanyoyin shafukan','Chọta ụzọ gị','Mọ ọ̀nà lílo'),steps:[
  text('Home shows your current position. Open each deal to see its own details.','Gida yana nuna halin da ake ciki. Buɗe kowace yarjejeniya don bayananta.','Ụlọ na-egosi ọnọdụ gị. Mepee nkwekọrịta ọ bụla maka nkọwa ya.','Ilé fi ipò rẹ hàn. Ṣí àdéhùn kọ̀ọ̀kan fún àlàyé rẹ.'),
  text('On a phone use the bottom menu; on a computer use the navigation menu.','A waya yi amfani da menu na ƙasa; a kwamfuta yi amfani da menu na gefe.','Na ekwentị jiri menu ala; na kọmputa jiri menu ụzọ.','Lórí fóònù lo àkójọ ìsàlẹ̀; lórí kọ̀ǹpútà lo àkójọ ọ̀nà.'),
  text('The bell shows updates. The role selector only opens portals you can access.','Ƙararrawa tana nuna sabuntawa. Mai zaɓen rawa yana buɗe wuraren da kake da izini.','Mgbịrịgba na-egosi mmelite. Nhọrọ ọrụ na-emepee naanị ngalaba enyere gị.','Agogo fi ìròyìn hàn. Àṣàyàn ipa ṣí abala tí o ní àṣẹ sí nìkan.'),
],tip:text('The guide button stays available above the bottom menu.','Maɓallin jagora yana nan sama da menu na ƙasa.','Bọtịnụ nduzi dị n’elu menu ala.','Bọ́tìnì ìtọ́nisọ́nà wà lókè àkójọ ìsàlẹ̀.')};
const profile:GuideTopic = {id:'profile',visual:'profile',href:'settings',title:text('Complete your profile','Cika bayanan kanka','Mejupụta profaịlụ gị','Parí àlàyé ara rẹ'),steps:[
  text('Open Settings. Check your name, phone, address and bank details.','Buɗe Saituna. Duba suna, waya, adireshi da bayanan banki.','Mepee Ntọala. Lelee aha, ekwentị, adreesị na nkọwa ụlọ akụ.','Ṣí Ètò. Ṣàyẹ̀wò orúkọ, fóònù, àdírẹ́sì àti àlàyé báńkì.'),
  text('Upload a clear JPG or PNG profile photo, no larger than 2 MB.','Saka hoton JPG ko PNG mai kyau, bai wuce 2 MB ba.','Bulite foto JPG ma ọ bụ PNG doro anya, ọ gafeeghị 2 MB.','Gbé fọ́tò JPG tàbí PNG tó ṣe kedere sókè, tí kò ju 2 MB lọ.'),
  text('Save changes. Choose English, Hausa, Igbo or Yoruba in Settings.','Ajiye canje-canje. Zaɓi Turanci, Hausa, Igbo ko Yoruba a Saituna.','Chekwaa mgbanwe. Họrọ Bekee, Hausa, Igbo ma ọ bụ Yoruba na Ntọala.','Fi àyípadà pamọ́. Yan Gẹ̀ẹ́sì, Hausa, Igbo tàbí Yorùbá nínú Ètò.'),
],tip:text('For organisations, check the business details and authorised representative too.','Ga ƙungiya, duba bayanan kasuwanci da wakilin da aka ba izini.','Maka ụlọ ọrụ, lelee nkọwa azụmahịa na onye nnọchiteanya enyere ikike.','Fún ilé-iṣẹ́, ṣàyẹ̀wò àlàyé iṣẹ́ àti aṣojú tó ní àṣẹ pẹ̀lú.')};
const kyc:GuideTopic = {id:'kyc',visual:'profile',href:'settings',title:text('Identity and bank verification','Tabbatar da shaida da banki','Nnyocha njirimara na ụlọ akụ','Ìjẹ́rìísí ìdánimọ̀ àti báńkì'),steps:[
  text('Clients and investors register with a valid government ID, BVN and bank details.','Abokan ciniki da masu jari suna rajista da shaidar gwamnati, BVN da bayanan banki.','Ndị ahịa na ndị itinye ego na-edebanye aha na ID gọọmentị, BVN na nkọwa ụlọ akụ.','Àwọn oníbàárà àti olùdókòwò forúkọsílẹ̀ pẹ̀lú ID ìjọba, BVN àti àlàyé báńkì.'),
  text('Investors also provide a TIN. Organisations identify their representative.','Masu jari suna bayar da TIN. Ƙungiyoyi suna bayyana wakilinsu.','Ndị itinye ego na-enyekwa TIN. Ụlọ ọrụ na-akọwa onye nnọchiteanya ha.','Olùdókòwò tún pèsè TIN. Ilé-iṣẹ́ sọ ẹni tó ń ṣojú wọn.'),
  text('Ask an admin to correct private KYC identifiers or replace identity documents.','Nemi mai gudanarwa ya gyara bayanan KYC na sirri ko ya sauya takardun shaida.','Rịọ onye nlekọta ka ọ dozie ozi KYC nzuzo ma ọ bụ dochie akwụkwọ ID.','Béèrè lọ́wọ́ alábòójútó láti tún KYC àṣírí ṣe tàbí rọ́pò ìwé ìdánimọ̀.'),
],tip:text('A correction may require verification again. Never send BVN or ID numbers in chat.','Gyara na iya buƙatar sake tabbatarwa. Kada ka aika BVN ko lambar shaida a hira.','Mgbanwe nwere ike ịchọ nyocha ọzọ. Ezipụla BVN ma ọ bụ nọmba ID na mkparịta ụka.','Àtúnṣe lè nílò ìjẹ́rìísí tuntun. Má fi BVN tàbí nọ́ńbà ID ránṣẹ́ nínú ìjíròrò.')};
const bank:GuideTopic = {id:'bank',visual:'bank',href:'dashboard',title:text('Choose where to pay','Zaɓi inda za ka biya','Họrọ ebe ị ga-akwụ ụgwọ','Yan ibi tí o máa sanwó sí'),steps:[
  text('Find NAL Payment Accounts on your dashboard or receipt page.','Nemo Asusun Biyan NAL a babban shafi ko shafin rasit.','Chọta Akaụntụ Ịkwụ NAL na ogwe gị ma ọ bụ ibe risit.','Wá Àwọn Àkọọ́lẹ̀ Ìsanwó NAL lórí pátákó tàbí ojú-ìwé risiti.'),
  text('Choose an available account and check its bank, name and number before transferring.','Zaɓi asusun da ke aiki, duba banki, suna da lamba kafin aika kuɗi.','Họrọ akaụntụ dị ma lelee ụlọ akụ, aha na nọmba tupu iziga ego.','Yan àkọọ́lẹ̀ tó wà, ṣàyẹ̀wò báńkì, orúkọ àti nọ́ńbà kí o tó fi owó ránṣẹ́.'),
  text('Pay through your banking app or bank, then keep the transfer receipt.','Biya ta manhajar banki ko bankin ka, sannan ajiye rasit.','Kwụọ site na ngwa ụlọ akụ gị ma ọ bụ ụlọ akụ, chekwaa risit.','Sanwó nípasẹ̀ ohun èlò báńkì rẹ tàbí báńkì, kí o sì pa risiti mọ́.'),
],tip:text('Selecting an account in NAL does not initiate a bank transfer.','Zaɓen asusu a NAL ba ya aika kuɗi daga banki.','Ịhọrọ akaụntụ na NAL anaghị eziga ego ụlọ akụ.','Yíyan àkọọ́lẹ̀ nínú NAL kò bẹ̀rẹ̀ fífi owó ránṣẹ́.')};
const receipt:GuideTopic = {id:'receipt',visual:'receipt',href:'receipts',title:text('Upload and verify a receipt','Saka rasit a tabbatar da shi','Bulite risit ka a nyochaa ya','Gbé risiti sókè fún ìjẹ́rìísí'),steps:[
  text('Choose Upload payment receipt or Upload contribution receipt. Take a photo or choose a JPEG, PNG or PDF up to 5 MB.','Zaɓi saka rasit na biya ko jari. Ɗauki hoto ko zaɓi JPEG, PNG ko PDF har 5 MB.','Họrọ bulite risit ụgwọ ma ọ bụ ntinye ego. Were foto ma ọ bụ họrọ JPEG, PNG ma ọ bụ PDF ruo 5 MB.','Yan gbígbé risiti ìsanwó tàbí ìdókòwò sókè. Ya fọ́tò tàbí yan JPEG, PNG tàbí PDF tí kò ju 5 MB lọ.'),
  text('Confirm the amount, date, reference and NAL account. Select the correct deal or investment purpose. Correct uncertain extraction.','Tabbatar da adadi, kwanan wata, lambar ma’amala da asusun NAL. Zaɓi yarjejeniya ko dalilin jari. Gyara abin da bai tabbata ba.','Kwenye ego, ụbọchị, ntụaka na akaụntụ NAL. Họrọ nkwekọrịta ma ọ bụ ebumnuche itinye ego. Dozie ihe amaghị nke ọma.','Jẹ́rìí iye, ọjọ́, àmì ìṣòwò àti àkọọ́lẹ̀ NAL. Yan àdéhùn tàbí ète ìdókòwò. Tún ohun tí kò dájú ṣe.'),
  text('Submit for verification. Track receipt history while admin matches the statement and approves posting.','Aika don tabbatarwa. Bi tarihin rasit yayin da mai gudanarwa ya daidaita shi da bayanin banki ya amince.','Zipụ maka nyocha. Soro akụkọ risit ka onye nlekọta jikọọ ya na nkwupụta ụlọ akụ ma kwado ya.','Fi ránṣẹ́ fún ìjẹ́rìísí. Tẹ̀lé ìtàn risiti bí alábòójútó ṣe ń bá ìwé báńkì mu tí ó sì ń fọwọ́ sí i.'),
],tip:text('Uploaded or Submitted is not Approved. AI extraction alone never credits your account.','An saka ko An aika ba yana nufin An amince ba. AI kaɗai ba ya ƙara kuɗi a asusu.','Ebulitere ma ọ bụ Ezipụrụ abụghị Akwadoro. Nnyocha AI naanị anaghị etinye ego na akaụntụ.','A gbé sókè tàbí A fi ránṣẹ́ kì í ṣe A fọwọ́ sí. AI nìkan kò fi owó kún àkọọ́lẹ̀.')};
const signing:GuideTopic = {id:'signing',visual:'signature',href:'agreements',title:text('Read, sign and keep agreements','Karanta, sa hannu, ajiye yarjejeniya','Gụọ, binye aka, chekwaa nkwekọrịta','Ka, fọwọ́ sí, pa àdéhùn mọ́'),steps:[
  text('Open Agreements and read every page. Check names, amounts, dates and repayment or investment terms.','Buɗe Yarjejeniyoyi ka karanta kowane shafi. Duba sunaye, adadi, ranaku da sharuɗɗa.','Mepee Nkwekọrịta ma gụọ ibe niile. Lelee aha, ego, ụbọchị na usoro ịkwụ ma ọ bụ itinye ego.','Ṣí Àdéhùn kí o ka gbogbo ojú-ìwé. Ṣàyẹ̀wò orúkọ, iye, ọjọ́ àti ìlànà ìsanwó tàbí ìdókòwò.'),
  text('Open the signing sheet. Draw with a finger, mouse, stylus or held-down trackpad click; the preview updates as you draw.','Buɗe takardar sa hannu. Zana da yatsa, linzamin kwamfuta, stylus ko riƙe danna trackpad; za ka ga hannun yana bayyana.','Mepee ibe mbinye aka. Jiri mkpịsị aka, mouse, stylus ma ọ bụ pịa trackpad mgbe ị na-adọta; ihe onyonyo na-apụta ozugbo.','Ṣí bébà ìfọwọ́sí. Lo ìka, mouse, stylus tàbí di títẹ trackpad mú bí o ṣe ń fà á; àwòrán ń farahàn lẹ́sẹ̀kẹsẹ̀.'),
  text('Clear and redraw if needed. Confirm only when satisfied; all required parties must sign before the agreement is fully executed.','Goge ka sake zana idan ya dace. Tabbatar idan ka gamsu; duk waɗanda ake buƙata sai sun sa hannu kafin kammalawa.','Hichaa ma see ọzọ ma ọ dị mkpa. Kwenye mgbe afọ juru gị; ndị niile achọrọ ga-abinye aka tupu nkwekọrịta zuru ezu.','Pa á rẹ́ kí o tún fà á bí ó bá yẹ. Jẹ́rìí nígbà tí ó tẹ́ ọ lọ́rùn; gbogbo ẹni tí a nílò gbọdọ̀ fọwọ́ sí kí àdéhùn tó pé.'),
],tip:text('A draft is not fully executed. Download or print the signed version and scan its QR code to verify authenticity.','Daftari ba yarjejeniya kammalalliya ba ce. Sauke ko buga wadda aka sa wa hannu, duba QR don tabbatar da sahihancinta.','Akwụkwọ mbido emezughị. Budata ma ọ bụ bipụta nke e binyere aka ma nyochaa QR iji hụ na ọ bụ eziokwu.','Àkọ́kọ́ ìwé kò tíì pé. Gbé èyí tí a fọwọ́ sí sílẹ̀ tàbí tẹ̀ ẹ́ jáde, ṣàyẹ̀wò QR fún ojúlówó rẹ̀.')};
const request:GuideTopic = {id:'request',visual:'workflow',href:'deals/request',title:text('Request financing','Nemi tallafin kuɗi','Rịọ ego azụmahịa','Béèrè ìnáwó'),steps:[
  text('Open Request. Describe the asset or business purpose and supply accurate proposed terms.','Buɗe Buƙata. Bayyana kadara ko manufar kasuwanci da sharuɗɗan da kake nema.','Mepee Arịrịọ. Kọwaa akụ ma ọ bụ ebumnuche azụmahịa na usoro ziri ezi.','Ṣí Ìbéèrè. Sọ ohun ìní tàbí ète iṣẹ́ àti ìlànà tí o ń dábàá.'),
  text('Submit once and follow the pending request. Admin reviews suitability and documentation.','Aika sau ɗaya ka bi buƙatar da ke jira. Mai gudanarwa yana nazarin dacewa da takardu.','Zipụ otu ugboro ma soro arịrịọ na-echere. Onye nlekọta na-enyocha ma ọ dabara na akwụkwọ.','Fi ránṣẹ́ lẹ́ẹ̀kan kí o tẹ̀lé ìbéèrè tó ń dúró. Alábòójútó ṣàyẹ̀wò ìbámu àti ìwé.'),
  text('If approved, check the final deal details and complete the required agreement and fee steps.','Idan an amince, duba bayanan ƙarshe ka cika yarjejeniya da kuɗin da ake buƙata.','Ọ bụrụ na a kwado, lelee nkọwa ikpeazụ ma mezue nkwekọrịta na ụgwọ achọrọ.','Bí a bá fọwọ́ sí, ṣàyẹ̀wò àlàyé ìkẹyìn kí o parí àdéhùn àti owó tí a nílò.'),
],tip:text('A request is not disbursement. Wait for the approved workflow to activate your deal.','Buƙata ba bayar da kuɗi ba ce. Jira amincewa don yarjejeniya ta fara aiki.','Arịrịọ abụghị nnyefe ego. Chere usoro nkwado ka nkwekọrịta malite.','Ìbéèrè kì í ṣe fífi owó fúnni. Dúró fún ìfọwọ́sí kí àdéhùn ṣiṣẹ́.')};
const guarantor:GuideTopic = {id:'guarantor',visual:'workflow',href:'agreements',title:text('Guarantor and witnesses','Mai garanti da shaidu','Onye nkwado na ndị akaebe','Onídùúró àti ẹlẹ́rìí'),steps:[
  text('Each client deal needs a guarantor. Check the guarantor details with NAL.','Kowace yarjejeniyar abokin ciniki na buƙatar mai garanti. Tabbatar da bayanansa da NAL.','Nkwekọrịta ahịa ọ bụla chọrọ onye nkwado. Lelee nkọwa ya na NAL.','Àdéhùn oníbàárà kọ̀ọ̀kan nílò onídùúró. Ṣàyẹ̀wò àlàyé rẹ̀ pẹ̀lú NAL.'),
  text('Create or obtain the correct guarantor and witness signing links and share them only with those signers.','Samu hanyoyin sa hannun mai garanti da shaida; aika su ga waɗannan mutane kawai.','Mepụta ma ọ bụ nweta njikọ mbinye aka onye nkwado na akaebe; kesaa ha naanị ndị ahụ.','Gba tàbí ṣẹ̀dá ọ̀nà ìfọwọ́sí onídùúró àti ẹlẹ́rìí; fi ránṣẹ́ sí wọn nìkan.'),
  text('Follow each signature status. Wakalah procurement authority applies only if admin grants it.','Bi matsayin kowane sa hannu. Izinin saye na Wakalah yana aiki idan mai gudanarwa ya bayar.','Soro ọnọdụ mbinye aka ọ bụla. Ikike ịzụ ahịa Wakalah dị naanị mgbe onye nlekọta nyere ya.','Tẹ̀lé ipò ìfọwọ́sí kọ̀ọ̀kan. Àṣẹ rírà Wakalah wà bí alábòójútó bá fúnni nìkan.'),
],tip:text('A signing link is private. Never sign on behalf of another person.','Hanyar sa hannu ta sirri ce. Kada ka sa hannu a madadin wani.','Njikọ mbinye aka bụ nzuzo. Ebinyeghị aka n’aha onye ọzọ.','Ọ̀nà ìfọwọ́sí jẹ́ àṣírí. Má fọwọ́ sí dípò ẹlòmíràn.')};
const schedule:GuideTopic = {id:'schedule',visual:'schedule',href:'deals',title:text('Track every active deal','Bi duk yarjejeniyoyin da ke aiki','Soro nkwekọrịta niile na-arụ ọrụ','Tẹ̀lé gbogbo àdéhùn tó ń ṣiṣẹ́'),steps:[
  text('Open Deals and select a deal to view its milestones, repayment schedule and payment history.','Buɗe Yarjejeniyoyi ka zaɓi ɗaya don matakai, jadawalin biya da tarihin biyan kuɗi.','Mepee Nkwekọrịta ma họrọ otu maka ọkwa, usoro ịkwụ na akụkọ ụgwọ.','Ṣí Àdéhùn kí o yan ọ̀kan fún ìpele, ètò ìsanwó àti ìtàn ìsanwó.'),
  text('Use the consolidated dashboard report when you have several active deals. Pay against the correct deal.','Yi amfani da rahoton haɗaka idan kana da yarjejeniyoyi masu aiki da yawa. Biya ga yarjejeniya daidai.','Jiri akụkọ jikọtara mgbe ị nwere ọtụtụ nkwekọrịta. Kwụọ maka nke ziri ezi.','Lo ìròyìn àpapọ̀ bí o bá ní ọ̀pọ̀ àdéhùn tó ń ṣiṣẹ́. Sanwó fún àdéhùn tó tọ́.'),
  text('Approved extra payments cover future installments within the outstanding deal balance. Check the updated schedule.','Ƙarin biyan da aka amince yana rufe biyan gaba cikin kuɗin da ya rage. Duba sabon jadawali.','Ụgwọ ọzọ akwadoro na-ekpuchi ụgwọ ga-abịa n’ime ego fọdụrụ. Lelee usoro ọhụrụ.','Àfikún ìsanwó tí a fọwọ́ sí bo ìsanwó ọjọ́ iwájú nínú iye tó kù. Ṣàyẹ̀wò ètò tuntun.'),
],tip:text('Only approved payments count. Uploading a receipt does not clear an installment.','Biyan da aka amince kawai ake ƙidaya. Saka rasit ba ya share biyan da ake bi.','Naanị ụgwọ akwadoro ka a na-agụ. Ịbulite risit anaghị ewepụ ụgwọ.','Ìsanwó tí a fọwọ́ sí nìkan ni a kà. Gbígbé risiti sókè kò parí ìsanwó.')};
const changes:GuideTopic = {id:'changes',visual:'schedule',href:'deals',title:text('Frequency changes and settlement','Canjin yawan biya da kammalawa','Mgbanwe ugboro ịkwụ na mmechi','Àyípadà ìgbà ìsanwó àti ìparí'),steps:[
  text('Open the deal and request a repayment-frequency change if needed.','Buɗe yarjejeniya ka nemi canjin yawan biya idan ya dace.','Mepee nkwekọrịta ma rịọ mgbanwe ugboro ịkwụ ma ọ dị mkpa.','Ṣí àdéhùn kí o béèrè àyípadà ìgbà ìsanwó bí ó bá yẹ.'),
  text('Keep following the current schedule until admin approves. The contract duration is not extended.','Ci gaba da jadawalin yanzu har sai an amince. Ba a ƙara tsawon yarjejeniya.','Soro usoro dị ugbu a ruo nkwado. A naghị agbatị oge nkwekọrịta.','Tẹ̀lé ètò tó wà títí a fi fọwọ́ sí. Àkókò àdéhùn kò ní gùn sí i.'),
  text('For early termination, request settlement and pay all remaining principal and profit; wait for admin confirmation.','Don ƙarewa da wuri, nemi kammalawa ka biya duk babban kuɗi da riba; jira tabbatarwar mai gudanarwa.','Maka nkwụsị mbụ, rịọ mmechi ma kwụọ isi ego na uru fọdụrụ; chere nkwenye onye nlekọta.','Fún ìparí ṣáájú àkókò, béèrè ìparí kí o san olú-owó àti èrè tó kù; dúró fún ìjẹ́rìísí alábòójútó.'),
],tip:text('Reminders use Lagos time: daily 4pm, weekly one day before, monthly three days before.','Tunatarwa tana amfani da lokacin Legas: kullum 4pm, mako kwana ɗaya kafin biya, wata kwana uku kafin biya.','Ncheta na-eji oge Lagos: kwa ụbọchị 4pm, kwa izu otu ụbọchị tupu, kwa ọnwa ụbọchị atọ tupu.','Ìránnilétí lo àkókò Lagos: ojoojúmọ́ 4pm, ọ̀sẹ̀ ọjọ́ kan ṣáájú, oṣù ọjọ́ mẹ́ta ṣáájú.')};
const printing:GuideTopic = {id:'printing',visual:'schedule',href:'deals',title:text('Print and keep your records','Buga ka ajiye bayananka','Bipụta ma chekwaa ndekọ gị','Tẹ̀ jáde kí o pa àkọsílẹ̀ mọ́'),steps:[
  text('Open a deal and use Print for its details and complete repayment schedule.','Buɗe yarjejeniya ka yi amfani da Buga don cikakken bayani da jadawalin biya.','Mepee nkwekọrịta ma jiri Bipụta maka nkọwa na usoro ịkwụ zuru ezu.','Ṣí àdéhùn kí o lo Tẹ̀ jáde fún àlàyé àti ètò ìsanwó kíkún.'),
  text('Allow all pages in the print dialog. Long schedules may span several pages.','Yarda da duk shafuka a akwatin bugawa. Dogon jadawali na iya wuce shafi ɗaya.','Kwe ka ibe niile pụta na igbe mbipụta. Usoro ogologo nwere ọtụtụ ibe.','Yan gbogbo ojú-ìwé nínú àpótí títẹ̀. Ètò gígùn lè ní ọ̀pọ̀ ojú-ìwé.'),
  text('Print agreements from Agreements or use Download PDF to save a copy.','Buga yarjejeniya daga Yarjejeniyoyi ko Sauke PDF don ajiye kwafi.','Bipụta akwụkwọ site na Nkwekọrịta ma ọ bụ Budata PDF iji chekwaa oyiri.','Tẹ̀ àdéhùn jáde láti Àdéhùn tàbí Gbé PDF sílẹ̀ láti pa ẹ̀dà mọ́.'),
],tip:text('Choose Save as PDF in your browser print dialog if you do not have a printer.','Zaɓi Ajiye a PDF a akwatin bugawar burauza idan ba ka da na’urar bugawa.','Họrọ Chekwaa dịka PDF na igbe mbipụta ma ọ bụrụ na ịnweghị igwe mbipụta.','Yan Fi pamọ́ bí PDF nínú àpótí títẹ̀ bí o kò bá ní ẹ̀rọ ìtẹ̀wé.')};
const investment:GuideTopic = {id:'investment',visual:'workflow',href:'dashboard',title:text('Follow your investment','Bi jarinka','Soro ntinye ego gị','Tẹ̀lé ìdókòwò rẹ'),steps:[
  text('Check portfolio totals, available capital and each investment on your dashboard.','Duba jimillar jari, kuɗin da ke akwai da kowane jari a babban shafi.','Lelee ego niile, isi ego dị na ntinye ego ọ bụla n’ogwe gị.','Ṣàyẹ̀wò iye àpapọ̀, olú-owó tó wà àti ìdókòwò kọ̀ọ̀kan lórí pátákó.'),
  text('For a new contribution, pay NAL and submit the receipt with the correct investment tenure.','Don sabon jari, biya NAL ka aika rasit da tsawon jarin daidai.','Maka ntinye ọhụrụ, kwụọ NAL ma zipụ risit na oge ntinye ziri ezi.','Fún ìdókòwò tuntun, sanwó sí NAL kí o fi risiti ránṣẹ́ pẹ̀lú àkókò tó tọ́.'),
  text('Review your Mudaraba agreement and complete your signature and both witness signatures.','Duba yarjejeniyar Mudaraba ka kammala hannunka da hannun shaidu biyu.','Lelee nkwekọrịta Mudaraba ma mezue aka gị na aka ndị akaebe abụọ.','Ṣàyẹ̀wò àdéhùn Mudaraba kí o parí ìfọwọ́sí rẹ àti ti ẹlẹ́rìí méjèèjì.'),
],tip:text('Expected profit is not realised profit. Read the actual agreed terms and account status.','Ribar da ake tsammani ba ribar da aka samu ba ce. Karanta sharuɗɗan da matsayin asusu.','Uru a tụrụ anya abụghị uru e nwetara. Gụọ usoro a kwadoro na ọnọdụ akaụntụ.','Èrè tí a retí kì í ṣe èrè tí a rí. Ka ìlànà tí a fohùn ṣọ̀kan àti ipò àkọọ́lẹ̀.')};
const withdrawal:GuideTopic = {id:'withdrawal',visual:'schedule',href:'dashboard',title:text('Know when funds are withdrawable','San lokacin cire kuɗi','Mara mgbe a pụrụ iwepụ ego','Mọ ìgbà tí a lè yọ owó'),steps:[
  text('Check the available withdrawal balance, not just total profit or invested capital.','Duba kuɗin da aka yarda a cire, ba jimillar riba ko jari kawai ba.','Lelee ego a pụrụ iwepụ, ọ bụghị naanị uru niile ma ọ bụ isi ego.','Ṣàyẹ̀wò iye tó ṣeé yọ, kì í ṣe èrè àpapọ̀ tàbí olú-owó nìkan.'),
  text('For a 90-day plan, realised profit releases at the end of each 30-day period; early client payment does not release it early.','Ga shirin kwana 90, ribar da aka samu tana buɗewa ƙarshen kowane kwana 30; biyan abokin ciniki da wuri ba ya buɗe ta da wuri.','Maka atụmatụ ụbọchị 90, uru e nwetara na-apụta na njedebe oge ụbọchị 30 ọ bụla; ụgwọ ahịa mbụ anaghị ewepụta ya ngwa ngwa.','Fún ètò ọjọ́ 90, èrè tí a rí di ṣíṣí ní òpin ọjọ́ 30 kọ̀ọ̀kan; ìsanwó oníbàárà ṣáájú kò ṣí i ṣáájú.'),
  text('Request withdrawal to your verified bank account or reinvest an eligible balance, then follow approval status.','Nemi cire kuɗi zuwa asusun da aka tabbatar ko sake zuba kuɗin da ya cancanta, sannan bi amincewa.','Rịọ mwepụ na akaụntụ ụlọ akụ a nyochara ma ọ bụ tinye ego tozuru ọzọ; soro nkwado.','Béèrè yíyọ sí àkọọ́lẹ̀ báńkì tí a jẹ́rìí tàbí tún iye tó yẹ dóko; tẹ̀lé ìfọwọ́sí.'),
],tip:text('Principal locks, longer-term limits and maturity dates follow your specific agreement.','Kulle jari, iyakokin lokaci mai tsawo da ranakun ƙarewa suna bin yarjejeniyarka.','Mkpọchi isi ego, oke oge ogologo na ụbọchị njedebe na-eso nkwekọrịta gị.','Ìdènà olú-owó, ààlà ìgbà gígùn àti ọjọ́ ìparí tẹ̀lé àdéhùn rẹ.')};
const zakat:GuideTopic = {id:'zakat',visual:'workflow',href:'dashboard',title:text('Zakat and transaction history','Zakka da tarihin ma’amala','Zakat na akụkọ azụmahịa','Zakat àti ìtàn ìṣòwò'),steps:[
  text('Check Transactions to follow confirmed deposits, returns, withdrawals and deductions.','Duba Ma’amaloli don kuɗin da aka tabbatar, dawowa, cirewa da cire-cire.','Lelee Azụmahịa maka ntinye, nloghachi, mwepụ na mbelata akwadoro.','Ṣàyẹ̀wò Ìṣòwò fún ìfowópamọ́, ìpadàbọ̀, yíyọ àti ayọkúrò tí a jẹ́rìí.'),
  text('Zakat eligibility uses your recorded Muslim status, nisab and the assessment anniversary.','Cancantar zakka tana amfani da matsayin Musulmi, nisabi da ranar cikar shekara.','Ikike Zakat na-eji ọnọdụ Muslim gị, nisab na ụbọchị ncheta nyocha.','Ìyẹ Zakat lo ipò Mùsùlùmí rẹ, nisab àti ọjọ́ ọdún ìṣàyẹ̀wò.'),
  text('If a record or eligibility status is wrong, contact admin before relying on the deduction.','Idan bayani ko cancanta ba daidai ba, tuntuɓi mai gudanarwa kafin amincewa da cirewar.','Ọ bụrụ na ndekọ ma ọ bụ ọnọdụ ezighi ezi, kpọtụrụ onye nlekọta tupu ịdabere na mbelata.','Bí àkọsílẹ̀ tàbí ìyẹ kò bá tọ́, kan sí alábòójútó kí o tó gbára lé ayọkúrò.'),
],tip:text('Do not infer a financial balance or religious status from an agreement alone.','Kada a ɗauki kuɗin asusu ko addini daga yarjejeniya kaɗai.','Ewepụla ego akaụntụ ma ọ bụ ọnọdụ okpukpe site naanị na nkwekọrịta.','Má ṣe pinnu iye àkọọ́lẹ̀ tàbí ipò ẹ̀sìn láti àdéhùn nìkan.')};
const help:GuideTopic = {id:'help',visual:'workflow',href:'dashboard',title:text('Get help safely','Samu taimako lafiya','Nweta enyemaka n’enweghị nsogbu','Gba ìrànlọ́wọ́ láìléwu'),steps:[
  text('Use Contact Admin or the message icon where available; check the bell for updates.','Yi amfani da Tuntuɓi Mai Gudanarwa ko alamar saƙo idan tana nan; duba ƙararrawa.','Jiri Kpọtụrụ Onye Nlekọta ma ọ bụ akara ozi ebe ọ dị; lelee mgbịrịgba.','Lo Kan sí Alábòójútó tàbí àmì ìfiránṣẹ́ níbi tí ó wà; ṣàyẹ̀wò agogo.'),
  text('For errors, keep the message and support reference. Hide private data before sharing a screenshot.','Ga kuskure, ajiye saƙo da lambar taimako. Ɓoye bayanan sirri kafin aika hoton allo.','Maka njehie, chekwaa ozi na ntụaka nkwado. Zoo ozi nzuzo tupu ịkekọrịta foto ihuenyo.','Fún àṣìṣe, pa ìfiránṣẹ́ àti àmì ìrànlọ́wọ́ mọ́. Bo àlàyé àṣírí kí o tó pín àwòrán ojú-ìwé.'),
  text('Retry loading if needed, but check history before resubmitting a payment or request.','Sake loda idan ya dace, amma duba tarihi kafin sake aika biyan kuɗi ko buƙata.','Megharia ibe ma ọ dị mkpa, mana lelee akụkọ tupu izipu ụgwọ ma ọ bụ arịrịọ ọzọ.','Tún ojú-ìwé sí bí ó bá yẹ, ṣùgbọ́n ṣàyẹ̀wò ìtàn kí o tó tún fi ìsanwó tàbí ìbéèrè ránṣẹ́.'),
],tip:text('Never share passwords, login codes, full BVN or API keys. WhatsApp delivery requires separate activation.','Kada ka raba kalmar sirri, lambar shiga, cikakken BVN ko API key. WhatsApp na buƙatar kunna shi daban.','Ekekọrịtala paswọọdụ, koodu nbanye, BVN zuru ezu ma ọ bụ igodo API. WhatsApp chọrọ ịgbalite iche.','Má pín ọ̀rọ̀ aṣínà, kóòdù ìwọlé, BVN kíkún tàbí API key. WhatsApp nílò ìmúṣiṣẹ́ lọ́tọ̀.')};

// Admin guides describe the actual human review gates, not automatic financial approval.
const adminUsers:GuideTopic = {id:'admin-users',visual:'profile',href:'users',title:text('Invite and maintain customers','Gayyata da kula da abokan ciniki','Kpọọ ma lekọta ndị ahịa','Pe àwọn oníbàárà kí o sì tọ́jú wọn'),steps:[
  text('Open Users. Invite a client, investor or authorised staff member with the appropriate role.','Buɗe Masu Amfani. Gayyaci abokin ciniki, mai jari ko ma’aikaci da rawar da ta dace.','Mepee Ndị Ọrụ. Kpọọ onye ahịa, itinye ego ma ọ bụ onye ọrụ na ọrụ kwesịrị ekwesị.','Ṣí Olùlò. Pe oníbàárà, olùdókòwò tàbí òṣìṣẹ́ pẹ̀lú ipa tó yẹ.'),
  text('Choose an individual or organisation and identify its authorised representative. Reuse an existing historical profile when appropriate.','Zaɓi mutum ko ƙungiya da wakilinta. Yi amfani da bayanin tarihi da ke akwai idan ya dace.','Họrọ onye ma ọ bụ ụlọ ọrụ na onye nnọchiteanya. Jiri profaịlụ ochie dị mgbe o kwesịrị.','Yan ẹni tàbí ilé-iṣẹ́ àti aṣojú rẹ̀. Lo àlàyé ìtàn tó wà bí ó bá yẹ.'),
  text('Open the user profile and choose Edit user records & uploads. Give an audit reason for corrections; review KYC again when required.','Buɗe bayanan mai amfani ka zaɓi gyara bayanai da takardu. Bayar da dalilin gyara; sake duba KYC idan ya dace.','Mepee profaịlụ ma họrọ dezie ndekọ na akwụkwọ. Nye ihe mere mgbanwe; nyochaa KYC ọzọ mgbe achọrọ.','Ṣí àlàyé olùlò kí o yan àtúnṣe àkọsílẹ̀ àti ìwé. Sọ ìdí àtúnṣe; tún KYC ṣàyẹ̀wò bí ó bá yẹ.'),
],tip:text('KYC editing does not rewrite executed agreements or posted financial transactions.','Gyaran KYC ba ya sauya yarjejeniyar da aka kammala ko ma’amalar da aka rubuta.','Mgbanwe KYC anaghị edegharị nkwekọrịta zuru ezu ma ọ bụ azụmahịa akwadoro.','Àtúnṣe KYC kò tún àdéhùn tí a parí tàbí ìṣòwò tí a kọ sílẹ̀ kọ.')};
const adminBank:GuideTopic = {...bank,id:'admin-bank',href:'settings',title:text('Set NAL receiving accounts','Saita asusun karɓar NAL','Hazie akaụntụ nnata NAL','Ṣètò àkọọ́lẹ̀ gbígba NAL'),steps:[
  text('Open Settings and NAL Payment Accounts. Add only verified NAL-owned accounts.','Buɗe Saituna da Asusun Biyan NAL. Ƙara asusun NAL da aka tabbatar kawai.','Mepee Ntọala na Akaụntụ Ịkwụ NAL. Tinye naanị akaụntụ NAL a nyochara.','Ṣí Ètò àti Àkọọ́lẹ̀ Ìsanwó NAL. Fi àkọọ́lẹ̀ NAL tí a jẹ́rìí kún un nìkan.'),
  text('Choose one active default account for notices and new agreements. Save the list.','Zaɓi asusun farko mai aiki don sanarwa da sabuwar yarjejeniya. Ajiye jerin.','Họrọ otu akaụntụ ndabara dị maka ozi na nkwekọrịta ọhụrụ. Chekwaa ndepụta.','Yan àkọọ́lẹ̀ àkọ́kọ́ tó ń ṣiṣẹ́ fún ìròyìn àti àdéhùn tuntun. Fi àkójọ pamọ́.'),
  text('Deactivate an old account instead of deleting its history. Upload statements separately for each account.','Kashe tsohon asusu maimakon share tarihinsa. Saka bayanin banki daban ga kowane asusu.','Gbanyụọ akaụntụ ochie kama ihichapụ akụkọ ya. Bulite nkwupụta maka akaụntụ ọ bụla iche.','Dá àkọọ́lẹ̀ àtijọ́ dúró dípò pípa ìtàn rẹ̀ rẹ́. Gbé ìwé báńkì kọ̀ọ̀kan sókè lọ́tọ̀.'),
],tip:text('Users choose among active accounts. Changing the default does not amend signed documents.','Masu amfani suna zaɓen asusun da ke aiki. Canjin asusun farko ba ya gyara takardun da aka sa wa hannu.','Ndị ọrụ na-ahọrọ akaụntụ dị. Ịgbanwe ndabara anaghị agbanwe akwụkwọ e binyere aka.','Olùlò yan lára àkọọ́lẹ̀ tó ń ṣiṣẹ́. Àyípadà àkọọ́lẹ̀ àkọ́kọ́ kò yí ìwé tí a fọwọ́ sí padà.')};
const reconciliation:GuideTopic = {id:'reconciliation',visual:'receipt',href:'reconciliation',title:text('Reconcile before approving money','Daidaita kafin amincewa da kuɗi','Jikọọ tupu ikwenye ego','Bá mu kí o tó fọwọ́ sí owó'),steps:[
  text('Upload a bank statement with the correct NAL account and coverage dates. Review every extracted row before confirming it.','Saka bayanin banki da asusun NAL da ranakun daidai. Duba kowane layi kafin tabbatarwa.','Bulite nkwupụta na akaụntụ NAL na ụbọchị ziri ezi. Lelee ahịrị ọ bụla tupu nkwenye.','Gbé ìwé báńkì sókè pẹ̀lú àkọọ́lẹ̀ NAL àti ọjọ́ tó tọ́. Ṣàyẹ̀wò ìlà kọ̀ọ̀kan kí o tó jẹ́rìí.'),
  text('Review the submitted receipt. Select the matching reviewed bank entry and record how it was verified.','Duba rasit da aka aika. Zaɓi layin banki da ya dace ka rubuta yadda aka tabbatar.','Lelee risit ezipụrụ. Họrọ ahịrị ụlọ akụ kwekọrọ ma dee otu e si nyochaa ya.','Ṣàyẹ̀wò risiti tí a fi ránṣẹ́. Yan àkọsílẹ̀ báńkì tó bá mu kí o kọ bí a ṣe jẹ́rìí rẹ̀.'),
  text('Approve financial posting only after reconciliation. Reject incorrect evidence with a clear reason.','Amince da rubuta kuɗi bayan daidaitawa kawai. Ƙi shaidar da ba daidai ba da dalili.','Kwado ndekọ ego naanị mgbe njikọ gasịrị. Jụ ihe akaebe ezighi ezi na ihe mere ya.','Fọwọ́ sí àkọsílẹ̀ owó lẹ́yìn ìbámu nìkan. Kọ ẹ̀rí tí kò tọ́ pẹ̀lú ìdí tó ṣe kedere.'),
],tip:text('AI suggests fields, not approvals. Pending or failed transfers and duplicate bank allocations must not be credited.','AI yana ba da bayanai, ba amincewa ba. Kada a ƙidaya biyan da ya gagara ko da aka maimaita.','AI na-atụ aro ozi, ọ bụghị nkwado. Ekwenyela ụgwọ na-echere, dara ada ma ọ bụ nke ugboro abụọ.','AI dábàá àlàyé, kì í ṣe ìfọwọ́sí. Má kà ìsanwó tó ń dúró, tó kùnà tàbí tí a tún pín sí.')};
const adminDeals:GuideTopic = {...request,id:'admin-deals',href:'deals',title:text('Review and activate deals','Duba ka kunna yarjejeniya','Nyochaa ma malite nkwekọrịta','Ṣàyẹ̀wò kí o mú àdéhùn ṣiṣẹ́'),steps:[
  text('Review Deal Requests or create a deal for the correct client. Verify costs, profit, duration, frequency and asset details.','Duba buƙata ko ƙirƙiri yarjejeniya ga abokin ciniki daidai. Duba kuɗi, riba, lokaci, biya da kadara.','Nyochaa arịrịọ ma ọ bụ mepụta nkwekọrịta maka onye kwesịrị. Lelee ọnụahịa, uru, oge, ugboro na akụ.','Ṣàyẹ̀wò ìbéèrè tàbí ṣẹ̀dá àdéhùn fún ẹni tó tọ́. Ṣàyẹ̀wò iye, èrè, àkókò, ìgbà àti ohun ìní.'),
  text('Record the required guarantor and decide whether the client receives Wakalah procurement authority. Complete signing gates.','Rubuta mai garanti, yanke ko abokin ciniki zai samu izinin Wakalah. Kammala sa hannu.','Dekọọ onye nkwado ma kpebie ikike Wakalah. Mezue mbinye aka achọrọ.','Kọ onídùúró sílẹ̀, pinnu àṣẹ Wakalah. Parí ìfọwọ́sí tí a nílò.'),
  text('Verify required management fees and eligible funding before activation. Attach procurement and disbursement evidence without deducting funds twice.','Tabbatar da kuɗin gudanarwa da jarin da ya cancanta kafin kunna aiki. Haɗa shaidar saye da bayarwa ba tare da cire kuɗi sau biyu ba.','Nyochaa ụgwọ nlekọta na ego tozuru tupu ịmalite. Tinye ihe akaebe ịzụ na nnyefe n’enweghị mbelata ugboro abụọ.','Jẹ́rìí owó ìṣàkóso àti ìnáwó tó yẹ kí o tó mú ṣiṣẹ́. So ẹ̀rí rírà àti fífúnni pọ̀ láìyọ owó lẹ́ẹ̀mejì.'),
],tip:text('Changing repayment frequency requires approval and must preserve the existing contractual maturity.','Canjin yawan biya yana buƙatar amincewa ba tare da sauya ranar ƙarewa ba.','Mgbanwe ugboro ịkwụ chọrọ nkwado ma ghara ịgbanwe ụbọchị njedebe.','Àyípadà ìgbà ìsanwó nílò ìfọwọ́sí, ó gbọdọ̀ pa ọjọ́ ìparí mọ́.')};
const imports:GuideTopic = {id:'imports',visual:'workflow',href:'historical-imports',title:text('Bring historical records into NAL','Shigar da bayanan tarihi a NAL','Tinye ndekọ ochie na NAL','Mú àkọsílẹ̀ àtijọ́ wọ NAL'),steps:[
  text('Reuse an existing customer or create an unclaimed profile. The snapshot date means records are accurate through that date, not the deal start.','Yi amfani da tsohon abokin ciniki ko ƙirƙiri bayanin da ba a karɓa ba. Ranar bayanai ita ce ranar da kuɗi suka kai, ba farkon yarjejeniya ba.','Jiri onye ahịa dị ma ọ bụ profaịlụ a na-azọrọbeghị. Ụbọchị ndekọ bụ ụbọchị ozi ziri ezi ruo ya, ọ bụghị mmalite nkwekọrịta.','Lo oníbàárà tó wà tàbí ṣẹ̀dá àlàyé tí a kò tíì gba. Ọjọ́ àkọsílẹ̀ túmọ̀ sí ọjọ́ tí àlàyé dé, kì í ṣe ọjọ́ ìbẹ̀rẹ̀ àdéhùn.'),
  text('Upload agreements, schedules and receipts. Extract or enter details, then mark each deal ongoing or completed and keep its original dates.','Saka yarjejeniya, jadawali da rasit. Ciro ko rubuta bayanai, nuna mai ci gaba ko kammalalle da ranakunsa na asali.','Bulite nkwekọrịta, usoro na risit. Wepụ ma ọ bụ tinye nkọwa, họrọ nke na-aga ma ọ bụ emechara na ụbọchị mbụ.','Gbé àdéhùn, ètò àti risiti sókè. Fa tàbí kọ àlàyé, samisi èyí tó ń lọ tàbí tó parí pẹ̀lú ọjọ́ àkọ́kọ́.'),
  text('Reconcile opening balances using evidence, resolve blocking issues, then approve and post. Invite the customer to claim that same account.','Daidaita kuɗin farko da shaida, warware matsaloli, sannan amince ka rubuta. Gayyaci abokin ciniki ya karɓi wannan asusun.','Jikọọ ego mbido na ihe akaebe, dozie ihe mgbochi, kwado ma depụta. Kpọọ onye ahịa ka o nweta otu akaụntụ ahụ.','Bá iye ìbẹ̀rẹ̀ mu pẹ̀lú ẹ̀rí, yanjú ìdènà, fọwọ́ sí kí o kọ sílẹ̀. Pe oníbàárà láti gba àkọọ́lẹ̀ kan náà.'),
],tip:text('An agreement alone is not evidence of available cash. Older receipts must not credit an opening balance again.','Yarjejeniya kaɗai ba shaidar kuɗin da ke akwai ba ce. Tsohon rasit ba zai ƙara kuɗin farko sau biyu ba.','Nkwekọrịta naanị abụghị ihe akaebe ego dị. Risit ochie agaghị etinye ego mbido ọzọ.','Àdéhùn nìkan kì í ṣe ẹ̀rí owó tó wà. Risiti àtijọ́ kò gbọdọ̀ fi kún iye ìbẹ̀rẹ̀ lẹ́ẹ̀kan sí i.')};
const reports:GuideTopic = {id:'reports',visual:'dashboard',href:'reports',title:text('Reports, funds and controls','Rahoto, kuɗi da kula','Akụkọ, ego na njikwa','Ìròyìn, owó àti ìṣàkóso'),steps:[
  text('Use Reports and Funds to compare approved transactions with capital, realised profit and spending.','Yi amfani da Rahoto da Kuɗi don kwatanta ma’amala da jari, ribar da aka samu da kashe kuɗi.','Jiri Akụkọ na Ego tụnyere azụmahịa akwadoro na isi ego, uru e nwetara na mmefu.','Lo Ìròyìn àti Owó láti fi ìṣòwò tí a fọwọ́ sí wé olú-owó, èrè tí a rí àti ìnáwó.'),
  text('Generate a printable Financial Report from a user profile; print signed agreements and deal schedules from their sections.','Ƙirƙiri Rahoton Kuɗi mai bugawa daga bayanin mai amfani; buga yarjejeniya da jadawali daga sassan su.','Mepụta Akụkọ Ego a pụrụ ibipụta site na profaịlụ; bipụta nkwekọrịta na usoro n’ebe ha.','Ṣẹ̀dá Ìròyìn Owó tó ṣeé tẹ̀ láti àlàyé olùlò; tẹ̀ àdéhùn àti ètò jáde ní abala wọn.'),
  text('Review Tax, Zakat settings, owner windows and Activity. Treat discrepancies as review items, not automatic corrections.','Duba Haraji, Zakka, lokacin masu mallaka da Ayyuka. A binciki bambance-bambance, ba a gyara su kai tsaye ba.','Lelee Ụtụ, Ntọala Zakat, oge onye nwe na Ihe Omume. Nyochaa ọdịiche; emezila ha ozugbo.','Ṣàyẹ̀wò Owó-orí, Zakat, àkókò olówó àti Ìgbòkègbodò. Ṣàyẹ̀wò ìyàtọ̀; má tún un ṣe láìṣàyẹ̀wò.'),
],tip:text('Read-only owners can inspect records but cannot approve or edit them.','Mai mallaka mai karatu kawai zai duba bayanai amma ba zai amince ko gyara ba.','Onye nwe nwere ịgụ naanị nwere ike ile ndekọ, ọ bụghị ikwenye ma ọ bụ dezie.','Olówó tó ní kíkà nìkan lè ṣàyẹ̀wò àkọsílẹ̀, kò lè fọwọ́ sí tàbí tún un ṣe.')};
const approvals:GuideTopic = {id:'approvals',visual:'workflow',href:'approvals/deposits',title:text('Review approval requests','Duba buƙatun amincewa','Nyochaa arịrịọ nkwado','Ṣàyẹ̀wò ìbéèrè ìfọwọ́sí'),steps:[
  text('Open the relevant Approvals category: deposits, repayments, withdrawals, reinvestments or terminations.','Buɗe sashen Amincewa da ya dace: saka kuɗi, biya, cirewa, sake jari ko ƙarewa.','Mepee ngalaba Nkwado kwesịrị: ntinye, ịkwụ, mwepụ, ntinye ọzọ ma ọ bụ nkwụsị.','Ṣí abala Ìfọwọ́sí tó yẹ: ìfowópamọ́, ìsanwó, yíyọ, ìdókòwò tuntun tàbí ìparí.'),
  text('Verify the customer, supporting evidence, available balance and contractual eligibility before deciding.','Tabbatar da abokin ciniki, shaida, kuɗin da ke akwai da sharuɗɗa kafin yanke shawara.','Nyochaa onye ahịa, ihe akaebe, ego dị na ikike nkwekọrịta tupu mkpebi.','Ṣàyẹ̀wò oníbàárà, ẹ̀rí, iye tó wà àti ìyẹ àdéhùn kí o tó pinnu.'),
  text('Approve or reject with the required checks. For frequency changes preserve maturity; check status before retrying.','Amince ko ƙi bayan bincike. Canjin yawan biya ba zai ƙara lokaci ba; duba matsayi kafin sake gwadawa.','Kwado ma ọ bụ jụ mgbe nyocha gasịrị. Maka ugboro ịkwụ chekwaa njedebe; lelee ọnọdụ tupu nnwale ọzọ.','Fọwọ́ sí tàbí kọ lẹ́yìn ìṣàyẹ̀wò. Pa ọjọ́ ìparí mọ́ fún àyípadà ìgbà; ṣàyẹ̀wò ipò kí o tó tún gbìyànjú.'),
],tip:receipt.tip};
const cases:GuideTopic = {id:'cases',visual:'workflow',href:'dashboard',title:text('Follow assigned recovery and legal cases','Bi shari’ar karɓar bashi da doka','Soro ọrụ mgbake na iwu enyere gị','Tẹ̀lé iṣẹ́ ìgbàpadà àti òfin tí a yàn'),steps:[
  text('Open an assigned case. Check the deal, outstanding balance, owner and next action.','Buɗe aikin da aka ba ka. Duba yarjejeniya, bashin da ya rage, jami’i da matakin gaba.','Mepee ọrụ enyere gị. Lelee nkwekọrịta, ego fọdụrụ, onye na-elekọta na omume ọzọ.','Ṣí iṣẹ́ tí a yàn sí ọ. Ṣàyẹ̀wò àdéhùn, iye tó kù, olùtọ́jú àti ìgbésẹ̀ tó kàn.'),
  text('Record contact outcomes, promises, next-action dates and supporting evidence; keep an accurate timeline.','Rubuta sakamakon tuntuɓa, alkawari, ranakun gaba da shaida; ajiye tarihin daidai.','Dekọọ nsonaazụ kọntaktị, nkwa, ụbọchị omume na ihe akaebe; debe akụkọ ziri ezi.','Kọ èsì ìbánisọ̀rọ̀, ìlérí, ọjọ́ ìgbésẹ̀ àti ẹ̀rí; pa ìtàn tó tọ́ mọ́.'),
  text('Use only the allowed case transitions. Escalate to legal or request closure through the authorised workflow.','Yi amfani da canje-canjen da aka yarda kawai. Miƙa zuwa doka ko nemi rufewa ta hanyar da aka amince.','Jiri naanị mgbanwe ọnọdụ enyere. Nyefee iwu ma ọ bụ rịọ mmechi site na usoro ikike.','Lo àyípadà ipò tí a gba nìkan. Gbé lọ sí òfin tàbí béèrè ìparí nípasẹ̀ àṣẹ.'),
],tip:text('A promise or settlement note is not a confirmed payment. Admin must reconcile and approve the money.','Alkawari ko bayanin sulhu ba biyan da aka tabbatar ba ne. Mai gudanarwa sai ya daidaita ya amince da kuɗi.','Nkwa ma ọ bụ ederede mmechi abụghị ụgwọ akwadoro. Onye nlekọta ga-enyocha ma kwado ego.','Ìlérí tàbí àkọsílẹ̀ ìparí kì í ṣe ìsanwó tí a jẹ́rìí. Alábòójútó gbọdọ̀ bá owó mu kí o fọwọ́ sí i.')};
const legal:GuideTopic = {...cases,id:'legal',title:text('Manage legal milestones','Kula da matakan doka','Jikwaa ọkwa iwu','Ṣàkóso ìpele òfin'),steps:[
  text('Review the case and related agreements. Prepare the notice with the correct parties and amounts.','Duba shari’a da yarjejeniya. Shirya sanarwa da mutanen da adadin daidai.','Nyochaa ọrụ na nkwekọrịta. Kwadebe akwụkwọ ozi na ndị na ego kwesịrị.','Ṣàyẹ̀wò iṣẹ́ àti àdéhùn. Pèsè ìkéde pẹ̀lú ẹni àti iye tó tọ́.'),
  text('Record approved notice service, counsel, court references, hearing dates and evidence as applicable.','Rubuta isar da sanarwa, lauya, lambar kotu, ranakun sauraro da shaida idan ya dace.','Dekọọ ozi enyere, ọka iwu, ntụaka ụlọikpe, ụbọchị ikpe na ihe akaebe ebe kwesịrị.','Kọ ìfijiṣẹ́ ìkéde, agbẹjọ́rò, àmì ilé-ẹjọ́, ọjọ́ ìgbọ́ràn àti ẹ̀rí bí ó bá yẹ.'),
  text('Record settlement terms and legal expenses accurately. Ask for admin review before final closure.','Rubuta sharuɗɗan sulhu da kuɗin doka daidai. Nemi nazarin mai gudanarwa kafin rufewa.','Dekọọ usoro mmechi na mmefu iwu nke ọma. Rịọ nyocha onye nlekọta tupu mmechi ikpeazụ.','Kọ ìlànà ìparí àti ìnáwó òfin dáadáa. Béèrè ìṣàyẹ̀wò alábòójútó kí o tó parí.'),
],tip:cases.tip};
const owner:GuideTopic = {id:'owner',visual:'dashboard',href:'dashboard',title:text('Read your owner position','Duba halin mai mallaka','Gụọ ọnọdụ onye nwe','Ka ipò olówó rẹ'),steps:[
  text('Review capital, liabilities, realised profit, expenses and partner allocations on the Owner Console.','Duba jari, nauyi, ribar da aka samu, kashe kuɗi da rabon abokan haɗin gwiwa a shafin Mai Mallaka.','Lelee isi ego, ụgwọ, uru e nwetara, mmefu na òkè ndị mmekọ n’ogwe Onye Nwe.','Ṣàyẹ̀wò olú-owó, gbèsè, èrè tí a rí, ìnáwó àti ìpín alábàáṣiṣẹ́ lórí pátákó Olówó.'),
  text('Check your available balance and withdrawal window before requesting a withdrawal.','Duba kuɗin da ke akwai da lokacin cirewa kafin neman cire kuɗi.','Lelee ego dị na oge mwepụ tupu ịrịọ mwepụ.','Ṣàyẹ̀wò iye tó wà àti àkókò yíyọ kí o tó béèrè yíyọ.'),
  text('Open Admin (Read-only) to inspect details. Use the role switcher to return to Owner Console.','Buɗe Admin na karatu kawai don cikakken bayani. Yi amfani da zaɓen rawa don dawowa shafin Mai Mallaka.','Mepee Admin (Ịgụ naanị) maka nkọwa. Jiri nhọrọ ọrụ laghachi ogwe Onye Nwe.','Ṣí Admin (Kíkà nìkan) láti ṣàyẹ̀wò. Lo àṣàyàn ipa láti padà sí pátákó Olówó.'),
],tip:reports.tip};
const referrals:GuideTopic = {id:'referrals',visual:'workflow',href:'dashboard',title:text('Track your referrals','Bi waɗanda ka gayyata','Soro ndị ị kpọrọ','Tẹ̀lé àwọn tí o tọ́ka'),steps:[
  text('Copy your referral code from the Marketer Dashboard and share it with prospective customers.','Kwafi lambar gayyata daga shafin Mai Talla ka raba ga abokan ciniki.','Detuo koodu ntụaka n’ogwe Onye Ahịa ma kesaa ndị ahịa ọhụrụ.','Da kóòdù ìtọ́kasí kọ láti pátákó Onítà, kí o pín fún oníbàárà tuntun.'),
  text('Customers enter the code when accepting their invitation. Follow referred clients and investors on your dashboard.','Abokan ciniki suna saka lambar lokacin karɓar gayyata. Bi abokan ciniki da masu jari a babban shafi.','Ndị ahịa na-etinye koodu mgbe ha na-anabata òkù. Soro ndị ahịa na itinye ego n’ogwe gị.','Oníbàárà tẹ kóòdù nígbà gbígba ìkésíni. Tẹ̀lé oníbàárà àti olùdókòwò lórí pátákó rẹ.'),
  text('Review referral counts, related deals and totals. Contact admin if attribution needs correction.','Duba adadin gayyata, yarjejeniyoyi da jimilla. Tuntuɓi mai gudanarwa idan dangantaka na buƙatar gyara.','Lelee ọnụọgụ ntụaka, nkwekọrịta na ego niile. Kpọtụrụ onye nlekọta ma ọ bụrụ na njikọ chọrọ mgbanwe.','Ṣàyẹ̀wò iye ìtọ́kasí, àdéhùn àti àpapọ̀. Kan sí alábòójútó bí àtọ́ka bá nílò àtúnṣe.'),
],tip:text('Referral visibility does not give permission to change customer finances or KYC.','Ganin gayyata ba ya ba da izinin gyaran kuɗi ko KYC na abokin ciniki.','Ịhụ ntụaka anaghị enye ikike ịgbanwe ego ma ọ bụ KYC ahịa.','Rírí ìtọ́kasí kò fún ọ ní àṣẹ láti yí owó tàbí KYC oníbàárà padà.')};

export function userGuideTopics(portal:PrimaryPortal, readOnlyAdmin = false):GuideTopic[] {
  if (portal==='client') return [navigation,profile,kyc,request,guarantor,signing,bank,receipt,schedule,changes,printing,help];
  if (portal==='investor') return [navigation,profile,kyc,bank,receipt,investment,signing,withdrawal,{...printing,href:'agreements',steps:[signing.steps[0],printing.steps[2],printing.tip]}, {...zakat,href:'transactions'},help];
  if (portal==='admin') return readOnlyAdmin ? [navigation,{...reports,href:'reports'}, {...signing,id:'inspect-agreements',steps:[signing.steps[0],text('Inspect signature status without signing or modifying the agreement.','Duba sa hannu ba tare da sa hannu ko gyara ba.','Lelee ọnọdụ aka n’enweghị ịbanye ma ọ bụ mgbanwe.','Ṣàyẹ̀wò ipò ìfọwọ́sí láìfọwọ́ sí tàbí tún un ṣe.'),printing.steps[2]]},help] : [navigation,adminUsers,adminBank,adminDeals,{...guarantor,href:'agreements'},signing,reconciliation,approvals,imports,{...cases,href:'dashboard'},reports,help];
  if (portal==='owner') return [navigation,owner,help];
  if (portal==='legal') return [navigation,cases,legal,help];
  if (portal==='recovery') return [navigation,cases,help];
  return [navigation,referrals,help];
}

export const GUIDE_VERSION = 1;
export type GuideProgress = {index:number;read:string[];dismissed:boolean};
export function guideStorageKey(uid:string, portal:PrimaryPortal, readOnly=false) {return `nal-guide-v${GUIDE_VERSION}:${uid}:${portal}:${readOnly?'read':'full'}`;}
export function parseGuideProgress(raw:string|null, topics:GuideTopic[]):GuideProgress {
  const empty={index:0,read:[],dismissed:false};
  try {if(!raw)return empty;const value=JSON.parse(raw);if(typeof value!=='object'||!value)return empty;return {index:Number.isInteger(value.index)?Math.max(0,Math.min(value.index,topics.length-1)):0,read:Array.isArray(value.read)?[...new Set<string>(value.read.filter((id:unknown)=>typeof id==='string'&&topics.some(topic=>topic.id===id)))]:[],dismissed:value.dismissed===true};}catch{return empty;}
}
