// It's not recommended to edit this file.
// This file is automatically generated by Firebase Studio.
// It reads the configuration from your .env file.

export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || "AIzaSyDYitdmm5H_7GkRR8PAmPMIyAQ9sS9Xggc",
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || "studio-1298078893-e7941.firebaseapp.com",
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || "studio-1298078893-e7941",
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || "studio-1298078893-e7941.appspot.com",
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || "1018583979606",
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || "1:1018583979606:web:d50ec535e8fbc4c231cdf7",
};
