/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/repayments` | `/repayments`; params?: Router.UnknownInputParams; } | { pathname: `/_auth_disabled/login`; params?: Router.UnknownInputParams; } | { pathname: `/_auth_disabled/register`; params?: Router.UnknownInputParams; } | { pathname: `/_tabs_disabled/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/_tabs_disabled/explore`; params?: Router.UnknownInputParams; } | { pathname: `/_tabs_disabled`; params?: Router.UnknownInputParams; } | { pathname: `/_tabs_disabled/login`; params?: Router.UnknownInputParams; } | { pathname: `/lib/repayments`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/repayments` | `/repayments`; params?: Router.UnknownOutputParams; } | { pathname: `/_auth_disabled/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_auth_disabled/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_tabs_disabled/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/_tabs_disabled/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/_tabs_disabled`; params?: Router.UnknownOutputParams; } | { pathname: `/_tabs_disabled/login`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/repayments`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/repayments${`?${string}` | `#${string}` | ''}` | `/repayments${`?${string}` | `#${string}` | ''}` | `/_auth_disabled/login${`?${string}` | `#${string}` | ''}` | `/_auth_disabled/register${`?${string}` | `#${string}` | ''}` | `/_tabs_disabled/dashboard${`?${string}` | `#${string}` | ''}` | `/_tabs_disabled/explore${`?${string}` | `#${string}` | ''}` | `/_tabs_disabled${`?${string}` | `#${string}` | ''}` | `/_tabs_disabled/login${`?${string}` | `#${string}` | ''}` | `/lib/repayments${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/repayments` | `/repayments`; params?: Router.UnknownInputParams; } | { pathname: `/_auth_disabled/login`; params?: Router.UnknownInputParams; } | { pathname: `/_auth_disabled/register`; params?: Router.UnknownInputParams; } | { pathname: `/_tabs_disabled/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/_tabs_disabled/explore`; params?: Router.UnknownInputParams; } | { pathname: `/_tabs_disabled`; params?: Router.UnknownInputParams; } | { pathname: `/_tabs_disabled/login`; params?: Router.UnknownInputParams; } | { pathname: `/lib/repayments`; params?: Router.UnknownInputParams; };
    }
  }
}
